# -*- mode: ruby -*-
# vi: set ft=ruby:

provisionPath = "initscripts/ansible-nfs.yaml"
testPath = "initscripts/test-nfs.sh"

nodes = [
	{:hostname => "nfs", :ip => "192.168.5.5", :cpus => 1, :mem => 512, :provisionScript => provisionPath, :testScript => testPath}
]


Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			vmachine.vm.box_download_insecure = true
			vmachine.vm.box = "peru/ubuntu-18.04-server-amd64"
			vmachine.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.network "private_network", ip: node[:ip]
			vmachine.vm.provider :libvirt do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			vmachine.vm.provision :ansible do |ansible|
    			ansible.playbook =  node[:provisionScript]
			end
			vmachine.vm.provision :shell, path: node[:testScript]
		end
	end
end
