# -*- mode: ruby -*-
# vi: set ft=ruby:

dnsscript = "initscripts/dnsinstall.sh"

nodes = [
	{:hostname => "dns", :ip => "192.168.5.3", :cpus => 1, :mem => 512, :script => dnsscript}
]


Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			config.vm.box_download_insecure = true
			config.vm.box = "peru/ubuntu-18.04-server-amd64"
			config.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.network "private_network", ip: node[:ip]
			vmachine.vm.provider :libvirt do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			vmachine.vm.provision :shell, path: node[:script]
		end
	end
end