# -*- mode: ruby -*-
# vi: set ft=ruby:

initscript = "initscripts/workerkubeinstall.sh"

nodes = [
#	... Define as much worker nodes as you want (do not exceed your system resources)
#	{:hostname => "node4", :ip => "192.168.5.14", :cpus => 2, :mem => 2048, :script => initscript},
#	{:hostname => "node3", :ip => "192.168.5.13", :cpus => 2, :mem => 2048, :script => initscript},
#	{:hostname => "node2", :ip => "192.168.5.12", :cpus => 2, :mem => 2048, :script => initscript},
	{:hostname => "node1", :ip => "192.168.5.11", :cpus => 2, :mem => 3072, :script => initscript}
]


Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |wmachine|
			config.vm.box_download_insecure = true
			config.vm.box = "peru/ubuntu-18.04-server-amd64"
			config.vm.box_check_update = false
			wmachine.vm.hostname = node[:hostname]
			wmachine.vm.network "private_network", ip: node[:ip]
			wmachine.vm.provider :libvirt do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			wmachine.vm.provision :shell, path: node[:script]
		end
	end
end