# -*- mode: ruby -*-
# vi: set ft=ruby:

initscript = "initscripts/workerkubeinstall.sh"

nodes = [
	{:hostname => "worker[[WORKER_N]]", :ip => "192.168.5.[[WORKER_IP]]", :cpus => 2, :mem => 3072, :script => initscript}
]


Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |wmachine|
			config.vm.box_download_insecure = true
			config.vm.box = "peru/ubuntu-18.04-server-amd64"
			config.vm.box_check_update = false
			wmachine.vm.hostname = node[:hostname]
			wmachine.vm.network "private_network", ip: node[:ip]
			wmachine.vm.provider :libvirt do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
				domain.management_network_domain = "devopsnet"
				domain.management_network_address = "10.20.30.0/24"
			end
			wmachine.vm.provision :shell, path: node[:script]
		end
	end
end